/*  =========================================================================
    zdiscgo - generated layer of public API

    Copyright (c) the Contributors as noted in the AUTHORS file.       
    This file is part of zdiscgo.                                      
                                                                       
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.           

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef ZDISCGO_LIBRARY_H_INCLUDED
#define ZDISCGO_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>

//  ZDISCGO version macros for compile-time API detection
#define ZDISCGO_VERSION_MAJOR 0
#define ZDISCGO_VERSION_MINOR 1
#define ZDISCGO_VERSION_PATCH 0

#define ZDISCGO_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define ZDISCGO_VERSION \
    ZDISCGO_MAKE_VERSION(ZDISCGO_VERSION_MAJOR, ZDISCGO_VERSION_MINOR, ZDISCGO_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined ZDISCGO_STATIC
#       define ZDISCGO_EXPORT
#   elif defined ZDISCGO_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define ZDISCGO_EXPORT __declspec(dllexport)
#       else
#           define ZDISCGO_EXPORT
#       endif
#   elif defined ZDISCGO_EXPORTS
#       define ZDISCGO_EXPORT __declspec(dllexport)
#   else
#       define ZDISCGO_EXPORT __declspec(dllimport)
#   endif
#   define ZDISCGO_PRIVATE
#else
#   define ZDISCGO_EXPORT
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define ZDISCGO_PRIVATE __attribute__ ((visibility ("hidden")))
#   else
#       define ZDISCGO_PRIVATE
#   endif
#endif

//  Project has no stable classes, so we build the draft API
#undef  ZDISCGO_BUILD_DRAFT_API
#define ZDISCGO_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
//  Draft classes are by default not built in stable releases
#ifdef ZDISCGO_BUILD_DRAFT_API
typedef struct _zdicgoplugin_t zdicgoplugin_t;
#define ZDICGOPLUGIN_T_DEFINED
typedef struct _zdiscgo_t zdiscgo_t;
#define ZDISCGO_T_DEFINED
#endif // ZDISCGO_BUILD_DRAFT_API


//  Public classes, each with its own header file
#ifdef ZDISCGO_BUILD_DRAFT_API
#include "zdicgoplugin.h"
#endif // ZDISCGO_BUILD_DRAFT_API

#ifdef ZDISCGO_BUILD_DRAFT_API
//  Self test for private classes
ZDISCGO_EXPORT void
    zdiscgo_private_selftest (bool verbose);
#endif // ZDISCGO_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
